export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';
export const GET_USERS_TO_INITIAL = 'GET_USERS_TO_INITIAL';

// SET PASSWORD FOR 'root'@'localhost' = PASSWORD('Amberq1w2e3r4t5');